#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "1 " "2 " "3 " "4 " "5 " "6 " "7 " "8 " "9 " "10 "

bspc config border_width         2
bspc config focused_border_color "#1199cc"
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr -s 1920x1080
feh --bg-scale ~/.config/bspwm/wallpapers/furry.jpg
${HOME}/.config/polybar/launch.sh
pulseaudio
pipewire
dunst &
